# Generated by Django 5.0.3 on 2024-03-21 05:27

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(upload_to=job.models.image_upload),
        ),
    ]
