# Generated by Django 5.0.3 on 2024-03-21 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_alter_job_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="job_tybe",
            new_name="job_type",
        ),
    ]
